### ISSUE TITLE
Add tokens for single text attribute

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/refinery-tokenizer#7]
For newly created attributes the whole project is tokenized to add the tokens for the new attribute.
To speed up the process and keep the already tokenized attributes working, we need a possibility to create tokens for the added attribute and add them to the already existing tokens (record_tokenized, docbin).
Similarly, it would be nice to have a way to remove these tokens again.

See
https://github.com/code-kern-ai/refinery-ac-exec-env/issues/3
https://github.com/code-kern-ai/refinery-ac-exec-env/issues/4

**Comment by FelixKirsch** [comment]
This is only an issue anymore for calculated text attributes. All other attributes are simply added to the docbin and the tokenization is not triggered again.
Removing user-created attributes without retokenization is also possible by now.

**Comment by JWittmeyer** [comment]
included in pr https://github.com/code-kern-ai/refinery-tokenizer/pull/17
